# Generated by Django 6.0.5 on 2026-05-15 13:50

import django.db.models.deletion
import standards.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_no', models.CharField(db_index=True, help_text='保留原始标准号，包含特殊前缀如"新Q/T"、"DBY"等，禁止清洗', max_length=200, verbose_name='标准号（原始）')),
                ('clean_id', models.CharField(db_index=True, help_text='用于检索的标准化标准号，前缀必须严格保留以区分不同标准体系', max_length=200, verbose_name='标准号（标准化）')),
                ('type', models.CharField(choices=[('enterprise', '企业标准'), ('group', '团体标准'), ('national', '国家标准'), ('industry', '行业标准'), ('local', '地方标准')], default='enterprise', max_length=20, verbose_name='标准类型')),
                ('title', models.CharField(blank=True, max_length=500, verbose_name='标准名称')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to=standards.models.pdf_upload_path, verbose_name='标准文件（PDF/Word）')),
                ('is_parsed', models.BooleanField(db_index=True, default=False, help_text='上传规范性引用 Excel 后自动标记为 True', verbose_name='是否已解析规范性引用')),
                ('citation_count', models.PositiveIntegerField(db_index=True, default=0, help_text='仅对国标有效，每次被企标规范性引用时 +1', verbose_name='被引用次数')),
                ('all_chain', models.JSONField(blank=True, default=list, help_text='JSON 数组，存储该标准在全生命周期中所有相关标准 ID', verbose_name='全生命周期链条')),
                ('part_chain', models.JSONField(blank=True, default=list, help_text='参考字段，统计时不使用，仅作展示辅助', verbose_name='部分链条（仅辅助）')),
                ('status', models.CharField(choices=[('active', '现行'), ('deprecated', '废止'), ('draft', '草案')], default='active', max_length=20, verbose_name='标准状态')),
                ('publish_date', models.DateField(blank=True, null=True, verbose_name='发布日期')),
                ('implement_date', models.DateField(blank=True, null=True, verbose_name='实施日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='入库时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='standards', to='companies.company', verbose_name='关联企业')),
            ],
            options={
                'verbose_name': '标准',
                'verbose_name_plural': '标准列表',
                'db_table': 'standards_standard',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NormativeReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cited_standard_no', models.CharField(db_index=True, max_length=200, verbose_name='被引用标准号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('cited_standard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cited_by', to='standards.standard', verbose_name='被引用标准（关联）')),
                ('source_standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normative_references', to='standards.standard', verbose_name='来源企标')),
            ],
            options={
                'verbose_name': '规范性引用',
                'verbose_name_plural': '规范性引用列表',
                'db_table': 'standards_normative_reference',
            },
        ),
        migrations.AddIndex(
            model_name='standard',
            index=models.Index(fields=['type', 'is_parsed'], name='idx_type_parsed'),
        ),
        migrations.AddIndex(
            model_name='standard',
            index=models.Index(fields=['citation_count'], name='idx_citation'),
        ),
        migrations.AlterUniqueTogether(
            name='normativereference',
            unique_together={('source_standard', 'cited_standard_no')},
        ),
    ]
