# Generated by Django 6.0.5 on 2026-05-17 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='standard',
            name='ccs',
            field=models.CharField(blank=True, db_index=True, help_text='中国标准文献分类号，如 L70', max_length=100, null=True, verbose_name='CCS分类号'),
        ),
        migrations.AddField(
            model_name='standard',
            name='ics',
            field=models.CharField(blank=True, db_index=True, help_text='国际标准分类号，如 35.240.50', max_length=100, null=True, verbose_name='ICS分类号'),
        ),
    ]
