# Generated by Django 6.0.5 on 2026-05-17 10:43

import standards.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standards', '0002_standard_ccs_standard_ics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standard',
            name='pdf_file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=standards.models.pdf_upload_path, verbose_name='标准文件（PDF/Word）'),
        ),
    ]
