# Generated by Django 6.0.5 on 2026-05-19 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standards', '0003_alter_standard_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='normativereference',
            name='latest_standard_no',
            field=models.CharField(blank=True, db_index=True, default='', max_length=200, verbose_name='最新标准号'),
        ),
    ]
