# Generated by Django 6.0.5 on 2026-05-20 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standards', '0004_normativereference_latest_standard_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='standard',
            name='disk_filename',
            field=models.CharField(blank=True, max_length=500, verbose_name='磁盘阵列文件路径'),
        ),
    ]
