# Generated by Django 6.0.5 on 2026-05-20 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standards', '0005_standard_disk_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standard',
            name='is_parsed',
            field=models.CharField(choices=[('unparsed', '暂未解析'), ('references_parsed', '已完成规范性引用解析'), ('indicators_parsed', '已完成指标解析')], db_index=True, default='unparsed', help_text='标准解析状态', max_length=50, verbose_name='解析状态'),
        ),
    ]
