# Generated by Django 6.0.5 on 2026-06-01 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standards', '0006_alter_standard_is_parsed'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField(verbose_name='页码')),
                ('content', models.TextField(blank=True, verbose_name='页面内容')),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='standards.standard', verbose_name='关联标准')),
            ],
            options={
                'verbose_name': '标准内容',
                'verbose_name_plural': '标准内容列表',
                'db_table': 'standards_standard_content',
                'ordering': ['page_number'],
                'unique_together': {('standard', 'page_number')},
            },
        ),
    ]
