# Generated by Django 6.0.5 on 2026-06-03 15:38

from django.db import migrations


def clear_relative_paths(apps, schema_editor):
    Standard = apps.get_model('standards', 'Standard')
    # Clear both pdf_file field starting with pdfs/
    Standard.objects.filter(pdf_file__startswith='pdfs/').update(pdf_file='')


def reverse_clear_relative_paths(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('standards', '0007_standardcontent'),
    ]

    operations = [
        migrations.RunPython(clear_relative_paths, reverse_clear_relative_paths),
    ]

