# Generated by Django 6.0.5 on 2026-08-14 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standards', '0008_clear_pdf_relative_paths'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standard',
            name='status',
            field=models.CharField(choices=[('active', '现行'), ('deprecated', '废止'), ('upcoming', '即将实施'), ('draft', '草案')], default='active', max_length=20, verbose_name='标准状态'),
        ),
    ]
