# Generated by Django 6.0.5 on 2026-06-03 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=150, verbose_name='用户名')),
                ('real_name', models.CharField(blank=True, max_length=150, verbose_name='真实姓名')),
                ('ip_address', models.CharField(blank=True, max_length=45, verbose_name='IP地址')),
                ('path', models.CharField(max_length=255, verbose_name='请求路径')),
                ('method', models.CharField(max_length=10, verbose_name='请求方式')),
                ('action', models.CharField(max_length=100, verbose_name='操作描述')),
                ('keyword', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='检索词')),
                ('target_id', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='目标ID')),
                ('status_code', models.IntegerField(verbose_name='状态码')),
                ('duration', models.FloatField(verbose_name='耗时(秒)')),
                ('is_warning', models.BooleanField(db_index=True, default=False, verbose_name='是否异常下载/越权警报')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='操作时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作用户')),
            ],
            options={
                'verbose_name': '使用日志',
                'verbose_name_plural': '使用日志',
                'db_table': 'statistics_usage_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='statistics__created_c21a96_idx'), models.Index(fields=['username'], name='statistics__usernam_85a9f4_idx'), models.Index(fields=['action'], name='statistics__action_6a0cb3_idx'), models.Index(fields=['is_warning'], name='statistics__is_warn_624ec3_idx')],
            },
        ),
    ]
