# Generated by Django 6.0.5 on 2026-05-15 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SmsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='目标手机号')),
                ('content', models.TextField(verbose_name='实际发送内容')),
                ('status', models.CharField(choices=[('success', '成功'), ('failed', '失败'), ('retry', '重试中')], max_length=20, verbose_name='发送状态')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('retry_count', models.PositiveSmallIntegerField(default=0, verbose_name='重试次数')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='发送时间')),
            ],
            options={
                'verbose_name': '短信发送日志',
                'verbose_name_plural': '短信发送日志',
                'db_table': 'notifications_sms_log',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='SmsTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_group', models.CharField(choices=[('all_active', '全部正常会员'), ('specific_company', '指定单位会员'), ('custom', '自定义手机号列表')], default='all_active', max_length=30, verbose_name='目标群体')),
                ('target_company', models.CharField(blank=True, max_length=200, verbose_name='指定单位（target_group=specific_company时填写）')),
                ('celery_task_id', models.CharField(blank=True, max_length=100, verbose_name='Celery 任务ID')),
                ('scheduled_time', models.DateTimeField(blank=True, null=True, verbose_name='计划执行时间')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='实际开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('status', models.CharField(choices=[('pending', '待执行'), ('running', '执行中'), ('done', '已完成'), ('failed', '失败'), ('partial', '部分成功')], default='pending', max_length=20, verbose_name='任务状态')),
                ('total_count', models.PositiveIntegerField(default=0, verbose_name='总发送目标数')),
                ('sent_count', models.PositiveIntegerField(default=0, verbose_name='成功发送数')),
                ('failed_count', models.PositiveIntegerField(default=0, verbose_name='失败数')),
                ('created_by', models.CharField(blank=True, max_length=50, verbose_name='创建人')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '短信任务',
                'verbose_name_plural': '短信任务列表',
                'db_table': 'notifications_sms_task',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SmsTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='模板名称')),
                ('content', models.TextField(help_text='支持变量: {name}=姓名, {company}=单位, {phone}=手机号', verbose_name='模板内容')),
                ('is_active', models.BooleanField(default=False, help_text='审核通过后方可被任务引用', verbose_name='是否已审核可用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '短信模板',
                'verbose_name_plural': '短信模板列表',
                'db_table': 'notifications_sms_template',
            },
        ),
    ]
