# Generated by Django 6.0.5 on 2026-05-15 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notifications', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='smslog',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_logs', to='users.member', verbose_name='目标会员'),
        ),
        migrations.AddField(
            model_name='smslog',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='notifications.smstask', verbose_name='所属任务'),
        ),
        migrations.AddField(
            model_name='smstask',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='notifications.smstemplate', verbose_name='使用模板'),
        ),
    ]
