# Generated by Django 6.0.5 on 2026-05-15 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('company', models.CharField(max_length=200, verbose_name='所属单位')),
                ('phone', models.CharField(db_index=True, max_length=20, verbose_name='手机号')),
                ('status', models.CharField(choices=[('active', '正常'), ('frozen', '冻结'), ('expired', '过期')], default='active', max_length=20, verbose_name='会员状态')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '会员',
                'verbose_name_plural': '会员列表',
                'db_table': 'users_member',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='用户名')),
                ('real_name', models.CharField(blank=True, max_length=50, verbose_name='真实姓名')),
                ('role', models.CharField(choices=[('superadmin', '超级管理员'), ('admin', '普通管理员'), ('operator', '操作员')], default='admin', max_length=20, verbose_name='角色')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('is_staff', models.BooleanField(default=False, verbose_name='是否可进入 Django Admin')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '管理员',
                'verbose_name_plural': '管理员列表',
                'db_table': 'users_admin',
            },
        ),
    ]
