# Generated by Django 6.0.5 on 2026-05-18 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='分类名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='分类编码')),
                ('is_system', models.BooleanField(default=False, verbose_name='是否系统默认')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '组织机构分类',
                'verbose_name_plural': '组织机构分类列表',
                'db_table': 'users_org_category',
                'ordering': ['created_at'],
            },
        ),
        migrations.AlterField(
            model_name='member',
            name='company',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='所属单位'),
        ),
        migrations.CreateModel(
            name='MemberOrgRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=200, verbose_name='机构/单位名称')),
                ('position', models.CharField(max_length=100, verbose_name='担任职务')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='加入时间')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='users.member', verbose_name='会员')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.organizationcategory', verbose_name='所属分类')),
            ],
            options={
                'verbose_name': '会员任职角色',
                'verbose_name_plural': '会员任职角色列表',
                'db_table': 'users_member_org_role',
                'ordering': ['joined_at'],
            },
        ),
    ]
