# Generated by Django 6.0.5 on 2026-05-20 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_organizationcategory_alter_member_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='role',
            field=models.CharField(choices=[('superadmin', '超级管理员'), ('admin', '普通管理员'), ('operator', '操作员'), ('client', '普通客户')], default='admin', max_length=20, verbose_name='角色'),
        ),
    ]
