# Generated by Django 6.0.5 on 2026-05-15 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='区划代码')),
                ('name', models.CharField(max_length=30, verbose_name='城市名称')),
            ],
            options={
                'verbose_name': '城市',
                'db_table': 'dict_city',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='区划代码')),
                ('name', models.CharField(max_length=20, verbose_name='省份名称')),
            ],
            options={
                'verbose_name': '省份',
                'db_table': 'dict_province',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='区划代码')),
                ('name', models.CharField(max_length=30, verbose_name='区县名称')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='companies.city')),
            ],
            options={
                'verbose_name': '区县',
                'db_table': 'dict_district',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='city',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='companies.province'),
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='企业名称')),
                ('credit_code', models.CharField(max_length=25, unique=True, verbose_name='统一社会信用代码')),
                ('legal_person', models.CharField(blank=True, max_length=50, verbose_name='法人')),
                ('latitude', models.DecimalField(blank=True, db_index=True, decimal_places=7, max_digits=10, null=True, verbose_name='纬度')),
                ('longitude', models.DecimalField(blank=True, db_index=True, decimal_places=7, max_digits=10, null=True, verbose_name='经度')),
                ('contact', models.CharField(blank=True, max_length=100, verbose_name='联系方式')),
                ('address', models.CharField(blank=True, max_length=500, verbose_name='详细地址')),
                ('status', models.CharField(choices=[('active', '正常'), ('disabled', '禁用')], default='active', max_length=20, verbose_name='状态')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='是否软删除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='companies.city', verbose_name='城市')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='companies.district', verbose_name='区县')),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='companies.province', verbose_name='省份')),
            ],
            options={
                'verbose_name': '企业',
                'verbose_name_plural': '企业列表',
                'db_table': 'companies_company',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['province', 'city', 'district'], name='idx_region'), models.Index(fields=['is_deleted', 'status'], name='idx_status')],
            },
        ),
    ]
