# Generated by Django 6.0.5 on 2026-05-18 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_city_latitude_city_longitude_district_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('wechat_mp', '微信公众号'), ('wechat_video', '视频号'), ('referral', '朋友介绍'), ('active_inquiry', '主动咨询'), ('other', '其他渠道')], default='active_inquiry', max_length=50, verbose_name='来访渠道')),
                ('contact_name', models.CharField(blank=True, max_length=100, verbose_name='联系人姓名')),
                ('contact_phone', models.CharField(blank=True, max_length=100, verbose_name='联系电话')),
                ('contact_wechat', models.CharField(blank=True, max_length=100, verbose_name='联系微信')),
                ('status', models.CharField(choices=[('pending', '待联系'), ('contacted', '已沟通'), ('interested', '意向会员'), ('vip_signed', '意向签约'), ('failed', '跟进失败')], default='pending', max_length=50, verbose_name='跟进状态')),
                ('memo', models.TextField(blank=True, verbose_name='沟通备注备忘录')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='companies.company', verbose_name='所属企业')),
            ],
            options={
                'verbose_name': '意向销售线索',
                'verbose_name_plural': '意向销售线索',
                'db_table': 'companies_lead',
                'ordering': ['-created_at'],
            },
        ),
    ]
