# Generated by Django 6.0.5 on 2026-05-29 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_companylead'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_size',
            field=models.CharField(blank=True, help_text='例如：大型、中型、小型、微型', max_length=50, verbose_name='企业规模'),
        ),
        migrations.AddField(
            model_name='company',
            name='company_type',
            field=models.CharField(blank=True, help_text='例如：有限责任公司、股份有限公司等', max_length=100, verbose_name='企业(机构)类型'),
        ),
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, help_text='企业的官方或联系邮箱', max_length=254, verbose_name='邮箱'),
        ),
        migrations.AddField(
            model_name='company',
            name='english_name',
            field=models.CharField(blank=True, help_text='企业英文名称', max_length=200, verbose_name='英文名'),
        ),
        migrations.AddField(
            model_name='company',
            name='established_date',
            field=models.DateField(blank=True, help_text='企业或机构的成立日期', null=True, verbose_name='成立日期'),
        ),
        migrations.AddField(
            model_name='company',
            name='former_names',
            field=models.CharField(blank=True, help_text='企业历史曾用名', max_length=500, verbose_name='曾用名'),
        ),
        migrations.AddField(
            model_name='company',
            name='industry_category',
            field=models.CharField(blank=True, help_text='国标行业分类门类名称或代码', max_length=100, verbose_name='国标行业门类'),
        ),
        migrations.AddField(
            model_name='company',
            name='industry_major',
            field=models.CharField(blank=True, help_text='国标行业分类大类', max_length=100, verbose_name='国标行业大类'),
        ),
        migrations.AddField(
            model_name='company',
            name='industry_middle',
            field=models.CharField(blank=True, help_text='国标行业分类中类', max_length=100, verbose_name='国标行业中类'),
        ),
        migrations.AddField(
            model_name='company',
            name='industry_minor',
            field=models.CharField(blank=True, help_text='国标行业分类小类', max_length=100, verbose_name='国标行业小类'),
        ),
        migrations.AddField(
            model_name='company',
            name='more_phones',
            field=models.CharField(blank=True, help_text='其他备用联系电话', max_length=200, verbose_name='更多电话'),
        ),
        migrations.AddField(
            model_name='company',
            name='organization_code',
            field=models.CharField(blank=True, help_text='组织机构代码证编号', max_length=100, verbose_name='组织机构代码'),
        ),
        migrations.AddField(
            model_name='company',
            name='registered_address',
            field=models.CharField(blank=True, help_text='企业营业执照上的注册地址', max_length=500, verbose_name='注册地址'),
        ),
        migrations.AddField(
            model_name='company',
            name='registered_zipcode',
            field=models.CharField(blank=True, help_text='注册地址对应的邮政编码', max_length=20, verbose_name='注册地址邮编'),
        ),
        migrations.AddField(
            model_name='company',
            name='registration_no',
            field=models.CharField(blank=True, help_text='工商注册号', max_length=100, verbose_name='注册号'),
        ),
        migrations.AddField(
            model_name='company',
            name='valid_mobile',
            field=models.CharField(blank=True, help_text='主要联系手机号码，用于接收重要推送或通知', max_length=50, verbose_name='有效手机号'),
        ),
    ]
