# Generated by Django 6.0.5 on 2026-05-29 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_company_company_size_company_company_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyLead',
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('wechat', '视频号/公众号'), ('phone', '电话咨询'), ('visit', '线下拜访'), ('other', '其他渠道')], default='other', max_length=50, verbose_name='来源')),
                ('req_type', models.CharField(choices=[('data_correction', '数据纠错'), ('business_cooperation', '业务合作'), ('general_inquiry', '常规咨询')], default='general_inquiry', max_length=50, verbose_name='诉求类型')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('following', '跟进中'), ('solved', '已解决/已成单'), ('closed', '无效关闭')], default='pending', max_length=50, verbose_name='跟进状态')),
                ('contact_name', models.CharField(blank=True, max_length=100, verbose_name='联系人姓名')),
                ('contact_phone', models.CharField(blank=True, max_length=100, verbose_name='联系电话')),
                ('contact_wechat', models.CharField(blank=True, max_length=100, verbose_name='联系微信')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL, verbose_name='负责人')),
                ('enterprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='companies.company', verbose_name='关联企业')),
            ],
            options={
                'verbose_name': 'CRM客户线索',
                'verbose_name_plural': 'CRM客户线索',
                'db_table': 'companies_lead',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='跟进内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='跟进时间')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followup_records', to=settings.AUTH_USER_MODEL, verbose_name='跟进人')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='companies.lead', verbose_name='关联线索')),
            ],
            options={
                'verbose_name': '线索跟进记录',
                'verbose_name_plural': '线索跟进记录',
                'db_table': 'companies_lead_followup',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='leads/attachments/', verbose_name='附件文件')),
                ('filename', models.CharField(max_length=255, verbose_name='原始文件名')),
                ('size', models.PositiveIntegerField(default=0, verbose_name='文件大小(Bytes)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='companies.lead', verbose_name='关联线索')),
            ],
            options={
                'verbose_name': '线索附件',
                'verbose_name_plural': '线索附件',
                'db_table': 'companies_lead_attachment',
                'ordering': ['-created_at'],
            },
        ),
    ]
