# Generated by Django 6.0.5 on 2026-05-29 14:31

from django.db import migrations, models
from django.conf import settings
import django.db.models.deletion

def copy_assignee_to_temp(apps, schema_editor):
    try:
        Lead = apps.get_model('companies', 'Lead')
        from django.contrib.auth import get_user_model
        User = get_user_model()
        User_model = apps.get_model(User._meta.app_label, User._meta.model_name)
        
        for lead in Lead.objects.all():
            if hasattr(lead, 'assignee_id') and lead.assignee_id:
                try:
                    user = User_model.objects.get(id=lead.assignee_id)
                    lead.assignee_temp = getattr(user, 'real_name', '') or user.username
                except Exception:
                    lead.assignee_temp = str(lead.assignee_id)
                lead.save(update_fields=['assignee_temp'])
    except Exception:
        pass

def seed_default_options(apps, schema_editor):
    LeadOption = apps.get_model('companies', 'LeadOption')
    from django.contrib.auth import get_user_model
    User = get_user_model()
    User_model = apps.get_model(User._meta.app_label, User._meta.model_name)

    # 1. Seed sources
    default_sources = [
        ('wechat', '视频号/公众号', 0),
        ('phone', '电话咨询', 1),
        ('visit', '线下拜访', 2),
        ('other', '其他渠道', 3),
    ]
    for val, name, order in default_sources:
        LeadOption.objects.get_or_create(option_type='source', value=val, defaults={'name': name, 'sort_order': order})
        
    # 2. Seed req_types
    default_reqs = [
        ('data_correction', '数据纠错', 0),
        ('business_cooperation', '业务合作', 1),
        ('general_inquiry', '常规咨询', 2),
    ]
    for val, name, order in default_reqs:
        LeadOption.objects.get_or_create(option_type='req_type', value=val, defaults={'name': name, 'sort_order': order})
        
    # 3. Seed statuses
    default_statuses = [
        ('pending', '待处理', 0),
        ('following', '跟进中', 1),
        ('solved', '已解决/已成单', 2),
        ('closed', '无效关闭', 3),
    ]
    for val, name, order in default_statuses:
        LeadOption.objects.get_or_create(option_type='status', value=val, defaults={'name': name, 'sort_order': order})

    # 4. Seed assignees from existing users
    try:
        users = User_model.objects.filter(is_active=True)
        for i, u in enumerate(users):
            name = getattr(u, 'real_name', '') or u.username
            LeadOption.objects.get_or_create(
                option_type='assignee',
                value=u.username,
                defaults={'name': name, 'sort_order': i}
            )
    except Exception as e:
        print(f"Skipped seeding assignees in migration: {e}")

class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_lead_followup_attachment_delete_companylead'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # 1. Create LeadOption model
        migrations.CreateModel(
            name='LeadOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_type', models.CharField(choices=[('req_type', '诉求类型'), ('source', '渠道来源'), ('status', '跟进状态'), ('assignee', '负责人')], max_length=20, verbose_name='配置项类型')),
                ('name', models.CharField(max_length=100, verbose_name='配置项名称/值')),
                ('value', models.CharField(max_length=100, verbose_name='对应键值(英文码/名称值)')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '线索自定义配置项',
                'verbose_name_plural': '线索自定义配置项',
                'db_table': 'companies_lead_option',
                'ordering': ['option_type', 'sort_order', 'name'],
                'unique_together': {('option_type', 'value')},
            },
        ),
        # 2. Seed options
        migrations.RunPython(seed_default_options),
        
        # 3. Alter other fields on Lead to CharField (remove choices/dynamic)
        migrations.AlterField(
            model_name='lead',
            name='req_type',
            field=models.CharField(default='general_inquiry', max_length=50, verbose_name='诉求类型'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(default='other', max_length=50, verbose_name='来源'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(default='pending', max_length=50, verbose_name='跟进状态'),
        ),
        
        # 4. Add temporary field assignee_temp
        migrations.AddField(
            model_name='lead',
            name='assignee_temp',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='负责人暂存'),
        ),
        # 5. Copy ForeignKey data to assignee_temp
        migrations.RunPython(copy_assignee_to_temp),
        # 6. Remove original ForeignKey assignee field
        migrations.RemoveField(
            model_name='lead',
            name='assignee',
        ),
        # 7. Rename assignee_temp to assignee
        migrations.RenameField(
            model_name='lead',
            old_name='assignee_temp',
            new_name='assignee',
        ),
        # 8. Set final field definition for assignee
        migrations.AlterField(
            model_name='lead',
            name='assignee',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='负责人'),
        ),
    ]
