# Generated by Django 6.0.5 on 2026-06-09 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_alter_lead_assignee_alter_lead_req_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='business_scope',
            field=models.TextField(blank=True, help_text='企业工商经营范围', verbose_name='经营范围'),
        ),
        migrations.AddField(
            model_name='company',
            name='mailing_address',
            field=models.CharField(blank=True, help_text='企业通讯地址', max_length=500, verbose_name='通讯地址'),
        ),
        migrations.AddField(
            model_name='company',
            name='mailing_address_zip',
            field=models.CharField(blank=True, help_text='通讯地址对应的邮政编码', max_length=20, verbose_name='通讯地址邮编'),
        ),
        migrations.AddField(
            model_name='company',
            name='registration_status',
            field=models.CharField(blank=True, help_text='工商登记状态（如：存续、在业、吊销、注销等）', max_length=100, verbose_name='工商状态'),
        ),
        migrations.AddField(
            model_name='company',
            name='website_url',
            field=models.CharField(blank=True, help_text='企业官方网站', max_length=500, verbose_name='官网网址'),
        ),
    ]
