# Generated by Django 6.0.5 on 2026-06-12 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_company_business_scope_company_mailing_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.CharField(blank=True, help_text='企业的官方或联系邮箱(可能包含多个)', max_length=1000, verbose_name='邮箱'),
        ),
    ]
