# Generated by Django 6.0.5 on 2026-06-12 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_alter_company_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.CharField(blank=True, help_text='企业的官方或联系邮箱(可包含多个)', max_length=254, verbose_name='邮箱'),
        ),
    ]
