# Generated by Django 6.0.5 on 2026-06-12 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_alter_company_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='standards_count',
            field=models.IntegerField(db_index=True, default=0, verbose_name='标准总数'),
        ),
    ]
