# Generated by Django 6.0.5 on 2026-08-14 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0010_company_standards_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='分类编码')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='分类名称')),
                ('category_type', models.CharField(choices=[('main', '主大类'), ('sub', '小类标签')], default='sub', max_length=20, verbose_name='分类类型')),
                ('definition', models.TextField(blank=True, help_text='国资委或法律法规标准权威定义', verbose_name='官方权威定义')),
                ('badge_color', models.CharField(blank=True, default='blue', help_text='前端展示 Badge 颜色', max_length=30, verbose_name='标签颜色')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序权重')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='companies.companycategory', verbose_name='所属父级分类')),
            ],
            options={
                'verbose_name': '企业所有制分类与标签',
                'verbose_name_plural': '企业所有制分类与标签',
                'db_table': 'companies_category',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='company',
            name='ownership_categories',
            field=models.ManyToManyField(blank=True, related_name='companies', to='companies.companycategory', verbose_name='所有制分类与标签'),
        ),
    ]
